import type { Bindings, Checkpoint, MemoryRecord } from '../types'

const now = () => new Date().toISOString()
export const seedMemories: MemoryRecord[] = [
  { id:'seed-product', title:'Memory.Nrul platform purpose', domain:'Project', memoryType:'instruction', summary:'General AI Memory and Context Continuity Platform.', content:'READ MEMORY → VERIFY CURRENT STATE → RECONSTRUCT CONTEXT → CONTINUE → EXECUTE → CHECKPOINT', privacyClass:'PUBLIC', status:'active', confidence:1, tags:['continuity','platform'], entities:['Memory.Nrul'], metadata:{seed:true}, createdAt:now(), updatedAt:now(), lastVerified:now() },
  { id:'seed-privacy', title:'External AI privacy boundary', domain:'System', memoryType:'constraint', summary:'RESTRICTED memory never reaches external providers.', content:'PUBLIC may be sent. PRIVATE requires explicit authorization. RESTRICTED is always blocked.', privacyClass:'PUBLIC', status:'active', confidence:1, tags:['privacy','security'], entities:[], metadata:{seed:true}, createdAt:now(), updatedAt:now(), lastVerified:now() },
]
let memories = [...seedMemories]
let checkpoints: Checkpoint[] = []

function parse<T>(value: unknown, fallback: T): T { try { return typeof value === 'string' ? JSON.parse(value) : fallback } catch { return fallback } }
export function rowToMemory(r: any): MemoryRecord { return { id:r.id,title:r.title,domain:r.domain,memoryType:r.memory_type,summary:r.summary,content:r.content,privacyClass:r.privacy_class,status:r.status,confidence:Number(r.confidence),source:r.source??undefined,tags:parse(r.tags_json,[]),entities:parse(r.entities_json,[]),metadata:parse(r.metadata_json,{}),validFrom:r.valid_from??undefined,validUntil:r.valid_until??undefined,supersedesId:r.supersedes_id??undefined,createdAt:r.created_at,updatedAt:r.updated_at,lastVerified:r.last_verified??undefined } }
export function rowToCheckpoint(r:any): Checkpoint { return { id:r.id,sessionId:r.session_id??undefined,summary:r.summary,currentState:r.current_state??undefined,completed:parse(r.completed_json,[]),pending:parse(r.pending_json??r.pending,[]),nextActions:parse(r.next_actions_json??r.next_actions,[]),decisions:parse(r.decisions_json,[]),constraints:parse(r.constraints_json,[]),createdAt:r.created_at } }

export class MemoryRepository {
  constructor(private env: Bindings) {}
  async list(includeArchived=false): Promise<MemoryRecord[]> { if(!this.env.DB) return memories.filter(m=>includeArchived||m.status==='active'); const sql=`SELECT * FROM memories ${includeArchived?'':'WHERE status = ?'} ORDER BY updated_at DESC`; const result=includeArchived?await this.env.DB.prepare(sql).all():await this.env.DB.prepare(sql).bind('active').all(); return (result.results||[]).map(rowToMemory) }
  async get(id:string): Promise<MemoryRecord|null> { if(!this.env.DB) return memories.find(m=>m.id===id)||null; const row=await this.env.DB.prepare('SELECT * FROM memories WHERE id = ?').bind(id).first(); return row?rowToMemory(row):null }
  async save(m:MemoryRecord): Promise<void> { if(!this.env.DB){ memories=[m,...memories.filter(x=>x.id!==m.id)]; return } await this.env.DB.prepare(`INSERT INTO memories (id,title,domain,memory_type,summary,content,privacy_class,status,confidence,source,tags_json,entities_json,metadata_json,valid_from,valid_until,supersedes_id,created_at,updated_at,last_verified) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,domain=excluded.domain,memory_type=excluded.memory_type,summary=excluded.summary,content=excluded.content,privacy_class=excluded.privacy_class,status=excluded.status,confidence=excluded.confidence,source=excluded.source,tags_json=excluded.tags_json,entities_json=excluded.entities_json,metadata_json=excluded.metadata_json,valid_from=excluded.valid_from,valid_until=excluded.valid_until,supersedes_id=excluded.supersedes_id,updated_at=excluded.updated_at,last_verified=excluded.last_verified`).bind(m.id,m.title,m.domain,m.memoryType,m.summary,m.content,m.privacyClass,m.status,m.confidence,m.source??null,JSON.stringify(m.tags),JSON.stringify(m.entities),JSON.stringify(m.metadata),m.validFrom??null,m.validUntil??null,m.supersedesId??null,m.createdAt,m.updatedAt,m.lastVerified??null).run() }
  async archive(id:string): Promise<boolean> { const m=await this.get(id); if(!m)return false; await this.save({...m,status:'archived',updatedAt:now()}); return true }
  async linksFor(ids:string[]):Promise<any[]> { if(!this.env.DB||!ids.length)return []; const marks=ids.map(()=>'?').join(','); const r=await this.env.DB.prepare(`SELECT * FROM memory_links WHERE source_id IN (${marks}) OR target_id IN (${marks})`).bind(...ids,...ids).all(); return r.results||[] }
  async listCheckpoints():Promise<Checkpoint[]> { if(!this.env.DB)return [...checkpoints].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); const r=await this.env.DB.prepare('SELECT * FROM checkpoints ORDER BY created_at DESC LIMIT 100').all(); return (r.results||[]).map(rowToCheckpoint) }
  async saveCheckpoint(cp:Checkpoint):Promise<void>{ if(!this.env.DB){checkpoints=[cp,...checkpoints.filter(x=>x.id!==cp.id)];return} await this.env.DB.prepare('INSERT INTO checkpoints (id,session_id,summary,current_state,completed_json,pending_json,next_actions_json,decisions_json,constraints_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(cp.id,cp.sessionId??null,cp.summary,cp.currentState??null,JSON.stringify(cp.completed),JSON.stringify(cp.pending),JSON.stringify(cp.nextActions),JSON.stringify(cp.decisions),JSON.stringify(cp.constraints),cp.createdAt).run() }
  async deleteCheckpoint(id:string):Promise<boolean>{ if(!this.env.DB){const n=checkpoints.length;checkpoints=checkpoints.filter(x=>x.id!==id);return n!==checkpoints.length} const r=await this.env.DB.prepare('DELETE FROM checkpoints WHERE id=?').bind(id).run(); return Number(r.meta.changes)>0 }
}
