import { Hono } from 'hono'

type Privacy = 'PUBLIC' | 'PRIVATE' | 'RESTRICTED'
type Status = 'active' | 'archived'
type MemoryType = 'fact' | 'preference' | 'decision' | 'situation' | 'task' | 'event' | 'relationship' | 'project' | 'handoff'

type Memory = {
  id: string; title: string; domain: string; summary: string; content: string; privacy: Privacy; status: Status
  confidence: number; source?: string; createdAt: string; updatedAt: string; lastVerified?: string
  memoryType: MemoryType; tags: string[]; entities: string[]; metadata: Record<string, unknown>
  validFrom?: string; validUntil?: string; supersedesId?: string
}

type Bindings = { DB?: D1Database; ASSETS?: Fetcher; MEMORY_ADMIN_KEY?: string }
const app = new Hono<{ Bindings: Bindings }>()

const seed: Memory[] = [
  { id:'m-001', title:'Memory.Nrul product direction', domain:'Project', summary:'General AI Memory & Context Continuity Platform.', content:'Preserve relevant continuity between conversations, sessions, models, and apps.', privacy:'PUBLIC', status:'active', confidence:1, createdAt:'2026-09-08', updatedAt:'2026-09-08', lastVerified:'2026-09-08', memoryType:'project', tags:['continuity','memory','ai'], entities:['Memory.Nrul'], metadata:{}, },
  { id:'m-002', title:'Continuity model', domain:'Conversation', summary:'Preserve shared understanding, decisions, situation, state, pending, and next actions.', content:'READ MEMORY → VERIFY CURRENT STATE → RECONSTRUCT CONTEXT → CONTINUE → EXECUTE → CHECKPOINT.', privacy:'PUBLIC', status:'active', confidence:1, createdAt:'2026-09-08', updatedAt:'2026-09-08', lastVerified:'2026-09-08', memoryType:'handoff', tags:['context','workflow'], entities:[], metadata:{}, },
  { id:'m-003', title:'Privacy boundary', domain:'Privacy', summary:'Sensitive context stays private and is only merged when authorized.', content:'PUBLIC is safe to expose. PRIVATE requires authorization. RESTRICTED is never returned to an unauthenticated caller.', privacy:'PUBLIC', status:'active', confidence:1, createdAt:'2026-09-08', updatedAt:'2026-09-08', lastVerified:'2026-09-08', memoryType:'decision', tags:['privacy','authorization'], entities:[], metadata:{}, }
]
let localMemories = [...seed]

function isAuthorized(c: { req:{ header(name:string):string|undefined }; env:Bindings }) { const k=c.env.MEMORY_ADMIN_KEY; return !!k && c.req.header('Authorization')===`Bearer ${k}` }
function visible(m:Memory, authorized:boolean) { return m.privacy==='PUBLIC' || authorized }
function now(){return new Date().toISOString()}
function id(){return `m-${crypto.randomUUID()}`}
function arr(v:any):string[]{return Array.isArray(v)?v.map(String).filter(Boolean):[]}
function obj(v:any):Record<string,unknown>{return v && typeof v==='object' && !Array.isArray(v)?v:{}}
function rowToMemory(r:any):Memory{return {id:r.id,title:r.title,domain:r.domain,summary:r.summary,content:r.content,privacy:r.privacy_class,status:r.status,confidence:Number(r.confidence??1),source:r.source??undefined,createdAt:r.created_at,updatedAt:r.updated_at,lastVerified:r.last_verified??undefined,memoryType:(r.memory_type||'fact') as MemoryType,tags:JSON.parse(r.tags_json||'[]'),entities:JSON.parse(r.entities_json||'[]'),metadata:JSON.parse(r.metadata_json||'{}'),validFrom:r.valid_from??undefined,validUntil:r.valid_until??undefined,supersedesId:r.supersedes_id??undefined}}
function payloadToMemory(body:any, existing?:Memory):Memory { const t=now(); return {id:existing?.id||id(),title:String(body.title||existing?.title||'').trim(),domain:String(body.domain||existing?.domain||'Conversation').trim(),summary:String(body.summary||existing?.summary||'').trim(),content:String(body.content??existing?.content??body.summary??'').trim(),privacy:(body.privacy||existing?.privacy||'PUBLIC') as Privacy,status:(body.status||existing?.status||'active') as Status,confidence:Number(body.confidence??existing?.confidence??1),source:body.source??existing?.source,createdAt:existing?.createdAt||t,updatedAt:t,lastVerified:body.lastVerified??existing?.lastVerified,memoryType:(body.memoryType||existing?.memoryType||'fact') as MemoryType,tags:arr(body.tags??existing?.tags),entities:arr(body.entities??existing?.entities),metadata:obj(body.metadata??existing?.metadata),validFrom:body.validFrom??existing?.validFrom,validUntil:body.validUntil??existing?.validUntil,supersedesId:body.supersedesId??existing?.supersedesId} }
function valid(m:Memory){return !!m.title&&!!m.summary&&['PUBLIC','PRIVATE','RESTRICTED'].includes(m.privacy)&&['active','archived'].includes(m.status)&&Number.isFinite(m.confidence)&&m.confidence>=0&&m.confidence<=1}
async function listMemories(c:{env:Bindings},authorized:boolean){if(c.env.DB){const rows=await c.env.DB.prepare('SELECT * FROM memories WHERE status=? ORDER BY updated_at DESC').bind('active').all<any>();return (rows.results||[]).map(rowToMemory).filter((m)=>visible(m,authorized))}return localMemories.filter(m=>m.status==='active'&&visible(m,authorized))}
function score(m:Memory,q:string){if(!q)return m.confidence;const tokens=q.toLowerCase().split(/\s+/).filter(Boolean);const hay=`${m.title} ${m.domain} ${m.summary} ${m.content} ${m.memoryType} ${m.tags.join(' ')} ${m.entities.join(' ')}`.toLowerCase();let hits=0;for(const t of tokens)if(hay.includes(t))hits++;const exact=m.title.toLowerCase().includes(q.toLowerCase())?3:0;const verified=m.lastVerified?1:0;const recency=Math.max(0,1-(Date.now()-new Date(m.updatedAt).getTime())/(1000*60*60*24*30));return hits*2+exact+verified+recency+m.confidence}
function ranked(memories:Memory[],q:string,limit=20){return [...memories].sort((a,b)=>score(b,q)-score(a,q)).slice(0,limit)}

app.get('/api/health',(c)=>c.json({ok:true,app:'Memory.Nrul',version:'0.3.0',persistence:c.env.DB?'d1':'memory-fallback',structuredMemory:true}))
app.get('/api/memories',async(c)=>{const authorized=isAuthorized(c),q=(c.req.query('q')||'').trim(),domain=c.req.query('domain')||'all',privacy=c.req.query('privacy')||'all';const all=await listMemories(c,authorized);const memories=ranked(all.filter(m=>(!domain||domain==='all'||m.domain===domain)&&(!privacy||privacy==='all'||m.privacy===privacy)),q);return c.json({memories,total:memories.length,authorized})})
app.get('/api/memories/:id',async(c)=>{const all=await listMemories(c,isAuthorized(c)),m=all.find(x=>x.id===c.req.param('id'));return m?c.json(m):c.json({error:'Memory not found'},404)})

app.post('/api/memories',async(c)=>{const body=await c.req.json<any>().catch(()=>({})),m=payloadToMemory(body);if(!valid(m))return c.json({error:'Invalid memory payload'},400);if(m.privacy!=='PUBLIC'&&!isAuthorized(c))return c.json({error:'Authorization required for private or restricted memory'},403);if(c.env.DB)await c.env.DB.prepare('INSERT INTO memories (id,title,domain,summary,content,privacy_class,status,confidence,source,created_at,updated_at,last_verified,memory_type,tags_json,entities_json,metadata_json,valid_from,valid_until,supersedes_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(m.id,m.title,m.domain,m.summary,m.content,m.privacy,m.status,m.confidence,m.source??null,m.createdAt,m.updatedAt,m.lastVerified??null,m.memoryType,JSON.stringify(m.tags),JSON.stringify(m.entities),JSON.stringify(m.metadata),m.validFrom??null,m.validUntil??null,m.supersedesId??null).run();else localMemories.unshift(m);return c.json(m,201)})
app.put('/api/memories/:id',async(c)=>{const authorized=isAuthorized(c),all=await listMemories(c,authorized),existing=all.find(m=>m.id===c.req.param('id'));if(!existing)return c.json({error:'Memory not found'},404);const m=payloadToMemory(await c.req.json<any>().catch(()=>({})),existing);if(!valid(m))return c.json({error:'Invalid memory payload'},400);if(m.privacy!=='PUBLIC'&&!authorized)return c.json({error:'Authorization required'},403);if(c.env.DB)await c.env.DB.prepare('UPDATE memories SET title=?,domain=?,summary=?,content=?,privacy_class=?,status=?,confidence=?,source=?,updated_at=?,last_verified=?,memory_type=?,tags_json=?,entities_json=?,metadata_json=?,valid_from=?,valid_until=?,supersedes_id=? WHERE id=?').bind(m.title,m.domain,m.summary,m.content,m.privacy,m.status,m.confidence,m.source??null,m.updatedAt,m.lastVerified??null,m.memoryType,JSON.stringify(m.tags),JSON.stringify(m.entities),JSON.stringify(m.metadata),m.validFrom??null,m.validUntil??null,m.supersedesId??null,m.id).run();else localMemories=localMemories.map(x=>x.id===m.id?m:x);return c.json(m)})
app.delete('/api/memories/:id',async(c)=>{if(!isAuthorized(c))return c.json({error:'Authorization required'},403);const id=c.req.param('id');if(c.env.DB)await c.env.DB.prepare('UPDATE memories SET status=? WHERE id=?').bind('archived',id).run();else localMemories=localMemories.map(m=>m.id===id?{...m,status:'archived',updatedAt:now()}:m);return c.json({ok:true,id,status:'archived'})})

app.get('/api/retrieve',async(c)=>{const q=c.req.query('q')||'',limit=Math.min(50,Math.max(1,Number(c.req.query('limit')||20))),authorized=isAuthorized(c);const memories=ranked(await listMemories(c,authorized),q,limit);return c.json({query:q,limit,results:memories.map(m=>({...m,relevance:Number(score(m,q).toFixed(3))}))})})
app.get('/api/context',async(c)=>{const q=c.req.query('q')||'',authorized=isAuthorized(c),memories=ranked(await listMemories(c,authorized),q,12);return c.json({currentContext:'General AI conversation continuity',sharedUnderstanding:'Memory preserves structured context rather than raw transcript.',currentState:'MVP → structured memory + persistence + CRUD + privacy + retrieval',domains:['Conversation','Personal','Relationship','Project','Decision','Situation','History','Preferences','Tasks','Session Handoff'],privacy:['PUBLIC','PRIVATE','RESTRICTED'],retrieved:memories,pending:['Authentication hardening','AI provider adapter','Import UI'],next:['AI context package','Checkpoint/handoff','Production deployment']})})
app.post('/api/context/package',async(c)=>{const authorized=isAuthorized(c),body=await c.req.json<any>().catch(()=>({})),query=String(body.query||''),memories=ranked(await listMemories(c,authorized),query,20);return c.json({version:'1.1',generatedAt:now(),purpose:'AI context continuity',instructions:['Use retrieved memory as context, not unquestionable truth.','Respect privacy classification and authorization.','Prefer recent, verified, high-confidence memory.','Use structured fields to preserve intent, decisions, state and pending work.'],query,context:memories.map(m=>({id:m.id,type:m.memoryType,domain:m.domain,title:m.title,summary:m.summary,content:m.content,tags:m.tags,entities:m.entities,metadata:m.metadata,confidence:m.confidence,updatedAt:m.updatedAt,lastVerified:m.lastVerified,validFrom:m.validFrom,validUntil:m.validUntil,supersedesId:m.supersedesId}))})})
app.get('/api/export',async(c)=>{if(!isAuthorized(c))return c.json({error:'Authorization required'},403);return c.json({version:'1.1',exportedAt:now(),memories:await listMemories(c,true)})})
app.post('/api/import',async(c)=>{if(!isAuthorized(c))return c.json({error:'Authorization required'},403);const body=await c.req.json<any>().catch(()=>({})),incoming=Array.isArray(body.memories)?body.memories:[];let imported=0;for(const raw of incoming){const m=payloadToMemory(raw);if(!valid(m))continue;if(c.env.DB)await c.env.DB.prepare('INSERT OR REPLACE INTO memories (id,title,domain,summary,content,privacy_class,status,confidence,source,created_at,updated_at,last_verified,memory_type,tags_json,entities_json,metadata_json,valid_from,valid_until,supersedes_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(m.id,m.title,m.domain,m.summary,m.content,m.privacy,m.status,m.confidence,m.source??null,m.createdAt,m.updatedAt,m.lastVerified??null,m.memoryType,JSON.stringify(m.tags),JSON.stringify(m.entities),JSON.stringify(m.metadata),m.validFrom??null,m.validUntil??null,m.supersedesId??null).run();else localMemories=[m,...localMemories.filter(x=>x.id!==m.id)];imported++}return c.json({ok:true,imported})})
app.get('*',async(c)=>{const url=new URL(c.req.url),asset=url.pathname==='/'?'/index.html':url.pathname;return c.env.ASSETS?c.env.ASSETS.fetch(new Request(new URL(asset,url))):c.notFound()})
export default app
